tap "oven-sh/bun"
brew "aom"
brew "xz"
brew "azure-cli"
brew "boost"
brew "glib"
brew "lima"
brew "colima"
brew "curl"
brew "docker"
brew "gcc"
brew "eccodes"
brew "ffuf"
brew "folly"
brew "fizz"
brew "libusb"
brew "gnupg"
brew "gpgme"
brew "jpeg-xl"
brew "libheif"
brew "libpq"
brew "poppler"
brew "gdal"
brew "gdk-pixbuf"
brew "harfbuzz"
brew "pango"
brew "ghostscript"
brew "git"
brew "git-filter-repo"
brew "gobuster"
brew "helm"
brew "imagemagick"
brew "inetutils"
brew "kubernetes-cli"
brew "librsvg"
brew "libusb-compat"
brew "lsusb"
brew "mas"
brew "midnight-commander"
brew "mole"
brew "needle"
brew "nmap"
brew "pmix"
brew "pv"
brew "qemu"
brew "trivy"
brew "vexctl"
brew "vips"
cask "balenaetcher"
cask "bruno"
cask "db-browser-for-sqlite"
cask "hex-fiend"
cask "omnidisksweeper"
cask "stats"
cask "warp"
cask "zed"
mas "Apple Configurator", id: 1037126344
mas "Cleaner for Xcode", id: 1296084683
mas "Developer", id: 640199958
mas "HP Smart", id: 1474276998
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Owly", id: 882812218
mas "Spark", id: 1176895641
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
vscode "aeschli.vscode-css-formatter"
vscode "alefragnani.project-manager"
vscode "bierner.color-info"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "brapifra.phpserver"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "docker.docker"
vscode "dsznajder.es7-react-js-snippets"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.code-runner"
vscode "humao.rest-client"
vscode "jock.svg"
vscode "johnpapa.vscode-peacock"
vscode "jundat95.react-native-snippet"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-aks-tools"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.azurecli"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "pnp.polacode"
vscode "qub.qub-xml-vscode"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "simonsiefke.svg-preview"
vscode "swmansion.react-native-ide"
vscode "twxs.cmake"
vscode "tyriar.lorem-ipsum"
vscode "vscode-icons-team.vscode-icons"
vscode "yzhang.markdown-all-in-one"
